### ISSUE TITLE
demo里面head的高度是写死的，如果是要在代码里计算高度怎么处理呢？

### ISSUE THREAD

**Issue by magic0908** [ShonLin/NetEaseProfileDemo#1]
在HomeFragment的initSlidingParams里，headerSize是直接指定212dp了。我这边的问题是，head的根布局是LinearLayout，里面有个TextView，TextView的文本是后台获取的，不固定的，可多可少，这样就会导致head的高度不固定，这样的话得怎么处理呢？

**Comment by lx8421bcd** [comment]
> 在HomeFragment的initSlidingParams里，headerSize是直接指定212dp了。我这边的问题是，head的根布局是LinearLayout，里面有个TextView，TextView的文本是后台获取的，不固定的，可多可少，这样就会导致head的高度不固定，这样的话得怎么处理呢？

可以考虑在TextView内容加载完成后调用getLayoutParams拿到TextView的高度，然后在Profile和List Fragment里面写方法让HomeFragment把参数传进去重设占位View高度和其它滑动参数

**Comment by magic0908** [comment]
谢谢！我在加载完数据后直接获取最外层的LinearLayout的高度了，这样可行。不过现在又有个问题，就是当fragment使用了懒加载，然后切换到对应的fragment后，连fragment的视图都加载不出来了。
